### ISSUE TITLE
allow gradle to include lib via JitPack repository dependency

### ISSUE THREAD

**Issue by k3b** [marianmoldovan/panoramagl#10]
If you tag the sourcecode of the lib with a version number **"0.1.1"** develeoppers can use the lib via jitpack like this:

Steps to use the lib 

**Step 1.** Add the JitPack repository to your build file
Add it in your root build.gradle at the end of repositories:
```groovy
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```

**Step 2.**  Add the dependency
```groovy
dependencies {
    implementation  'com.github.marianmoldovan:panoramagl:0.1.1'
}
```

if you add a tag in the git repository can you also add the "Steps to use the lib" to Reademe.md ? 

Update 2018-10-27:

Currently jitpack builds [fails with error message](https://github.com/jitpack/jitpack.io/issues/3484)

>  No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

Google has removed ABI cpu support and old buildtools fail because they check for "ABI" :-(

See https://stackoverflow.com/questions/35128229/error-no-toolchains-found-in-the-ndk-toolchains-folder-for-abi-with-prefix-llv for details.

To fix this you also have to upgrade build-tools and the gradle version, too

> classpath "com.android.tools.build:gradle:3.2.0"

If you want i can do this for you and provide you a merge request for this.

I have already done this for https://github.com/k3b/SimplePanorama that uses "panoramagl"

Using more recent gradle/build tools via jitpack may also solve https://github.com/marianmoldovan/panoramagl/issues/9

**Comment by hannesa2** [comment]
It works now with jitack.io https://jitpack.io/#marianmoldovan/panoramagl

	dependencies {
	        implementation 'com.github.marianmoldovan:panoramagl:1.0'
	}
