### ISSUE TITLE
jetpack build error 1.9.0 version

### ISSUE THREAD

**Issue by mupm1** [marianmoldovan/panoramagl#116]
![image](https://user-images.githubusercontent.com/7701890/137123391-9fe28ffe-c99a-4322-b3d9-5f1547348dcb.png)

**Comment by hannesa2** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/3314607/137125233-878d1f5a-7dbf-4708-9efc-2a9a25913cf7.png">
-wtf-
