### ISSUE TITLE
Does not support ARM v9 Nexus 6P

### ISSUE THREAD

**Issue by CodeCombiner** [marianmoldovan/panoramagl#2]
Hi @marianmoldovan , thanx for cool gradle adaptation of the library. I tried to do it myself but it seems eclipse project does not support Android 6. I tried this repository and it runs successfully on Android 6 but not on Nexus 6P. Do you have any suggestions how it can be fixed?

I build library with tools v23 and set APP_ABI := all. I got this warning in eclipse

`jni/com_panoramagl_opengl_GLUES.c: In function 'gluesCallErrorCallback':
jni/com_panoramagl_opengl_GLUES.c:76:77: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    (*env)->CallStaticVoidMethod(env, sclass, methodID, (jvalue*)qobj, (jint)(jvalue*)(jint)gluesErrorCode);
`
Can this warning be related to Nexus 6P error?

Any suggestions appreciated

**Comment by marianmoldovan** [comment]
Hi, can you try to get the crash logs, maybe removing the app/package filter.

**Comment by CodeCombiner** [comment]
I am not sure why, but after I built with APP_ABI := all and restarted Android Studio it works fine
