### ISSUE TITLE
64 bits support

### ISSUE THREAD

**Issue by PhilippeTroller** [marianmoldovan/panoramagl#9]
Ty for this awsome library. 
For information,  i ported it on Xamarin Android, it works really well.
I still have a pb :   panoramagl doesn't support x86_64 and arm64-v8a arhitecture. 
Can you confirm this point ? Or did i miss something ? 
There isn't any 64 bits versions of libglues.so ? Any help, advice on this point would really be appreciated.
64 bits will be mandatory in 2019. So ...
Ty in advance.

**Comment by ahmadhariss** [comment]
This guy has the source code of the files:
https://github.com/waylife/panoramagl-android/tree/master/panoramagl-android/PanoramaGL/jni

Access this directory and use command ndk-build using terminal.

Also you need to modify Application.mk ABIs to all.

as a result you will find in console the needed files.

**Comment by ahmadhariss** [comment]
[libs.zip](https://github.com/marianmoldovan/panoramagl/files/3224081/libs.zip)
and here is the files incase you dont want to do the whole process.

**Comment by KrishanMadushanka** [comment]
@ahmadhariss thanks for the files.(libs.zip)

**Comment by marianmoldovan** [comment]
Solved by https://github.com/marianmoldovan/panoramagl/pull/11

**Comment by hannesa2** [comment]
Here is the C code https://github.com/hannesa2/panoramagl/pull/38
